# Generated by Django 3.2.9 on 2021-11-29 14:43

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Artist',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('artist_name', models.CharField(max_length=32)),
                ('artist_image', models.ImageField(blank=True, null=True, upload_to='artist/image/%Y/%m/%d/%H')),
                ('artist_image_url', models.URLField(blank=True, default='')),
            ],
        ),
        migrations.CreateModel(
            name='ArtWork',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('artwork_title', models.CharField(blank=True, max_length=100, null=True)),
                ('artwork_image', models.ImageField(blank=True, null=True, upload_to='artwork/image/%Y/%m/%d/%H')),
                ('artwork_image_url', models.URLField(blank=True, default='')),
                ('artwork_auction', models.CharField(blank=True, max_length=32, null=True)),
                ('artwork_price', models.IntegerField(blank=True, null=True)),
                ('artwork_price_ho', models.FloatField(blank=True, null=True)),
                ('artwork_year', models.CharField(blank=True, max_length=32, null=True)),
                ('artwork_trade_date', models.DateField(blank=True, null=True)),
                ('artwork_genre', models.CharField(blank=True, max_length=32, null=True)),
                ('artwork_material', models.CharField(blank=True, max_length=32, null=True)),
                ('artwork_size_width', models.CharField(blank=True, max_length=32, null=True)),
                ('artwork_size_height', models.CharField(blank=True, max_length=32, null=True)),
                ('artist', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='price.artist')),
            ],
        ),
        migrations.CreateModel(
            name='ArtistComments',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content', models.TextField()),
                ('create_date', models.DateTimeField()),
                ('modify_date', models.DateTimeField(blank=True, null=True)),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('post', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='price.artist')),
            ],
        ),
    ]
