# Generated by Django 3.2.9 on 2021-11-23 07:47

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Artist',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('artist_name', models.CharField(max_length=32)),
                ('artist_image', models.ImageField(blank=True, null=True, upload_to='artist/image/%Y/%m/%d/%H')),
                ('artist_image_url', models.URLField(blank=True, default='')),
            ],
        ),
        migrations.CreateModel(
            name='ArtWork',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('artwork_title', models.CharField(max_length=100)),
                ('artwork_image', models.ImageField(blank=True, null=True, upload_to='artwork/image/%Y/%m/%d/%H')),
                ('artwork_image_url', models.URLField(blank=True, default='')),
                ('artwork_price', models.IntegerField()),
                ('artwork_trade_date', models.DateField()),
                ('artwork_material', models.CharField(max_length=32)),
                ('artwork_size_width', models.CharField(max_length=32)),
                ('artwork_size_height', models.CharField(max_length=32)),
                ('artist', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='artist_set', to='price.artist')),
            ],
        ),
    ]
