# Generated by Django 3.2.9 on 2021-11-22 04:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('price', '0002_alter_artwork_artist'),
    ]

    operations = [
        migrations.AlterField(
            model_name='artist',
            name='image',
            field=models.ImageField(upload_to='artist/image/%Y/%m/%d/%H'),
        ),
        migrations.AlterField(
            model_name='artwork',
            name='art_image',
            field=models.ImageField(upload_to='artwork/image/%Y/%m/%d/%H'),
        ),
    ]
