# Generated by Django 3.2.9 on 2021-11-22 05:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('price', '0003_auto_20211122_1327'),
    ]

    operations = [
        migrations.AddField(
            model_name='artwork',
            name='art_image_url',
            field=models.URLField(blank=True, default=''),
        ),
        migrations.AlterField(
            model_name='artist',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='artist/image/%Y/%m/%d/%H'),
        ),
        migrations.AlterField(
            model_name='artwork',
            name='art_image',
            field=models.ImageField(blank=True, null=True, upload_to='artwork/image/%Y/%m/%d/%H'),
        ),
    ]
