# Generated by Django 3.2.9 on 2021-11-28 17:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('collection', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='collectionpost',
            name='subject',
            field=models.CharField(max_length=200, null=True),
        ),
    ]
