# Generated by Django 3.2.9 on 2021-11-28 17:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('collection', '0002_alter_collectionpost_subject'),
    ]

    operations = [
        migrations.AlterField(
            model_name='collectionpost',
            name='subject',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
