# Generated by Django 3.2.8 on 2021-11-04 00:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('board', '0003_boardanswer_author'),
    ]

    operations = [
        migrations.AddField(
            model_name='boardanswer',
            name='modify_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='boardpost',
            name='modify_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
