# Generated by Django 3.2.9 on 2021-11-22 01:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('board', '0004_auto_20211104_0957'),
    ]

    operations = [
        migrations.AddField(
            model_name='boardpost',
            name='category',
            field=models.CharField(max_length=32, null=True),
        ),
        migrations.AddField(
            model_name='boardpost',
            name='head_image',
            field=models.ImageField(blank=True, null=True, upload_to='board/image/%Y/%m/%d/%H'),
        ),
    ]
